### ISSUE TITLE
Feature request: Proxy post request to hide IP of user

### ISSUE THREAD

**Issue by Bramzor** [simpleanalytics/cdn#2]
Just checked the code and I was wondering if I could just update the hostname and cdn parameter inside hello.js to pass this towards a script on our server which can do the POST of the JSON data and therefore hide the IP of the user and possibly some other headers which might leak user info as well?

Would also be nice if we could pass a country parameter too. So Analytics would have country information (so it could show a map) without ever seeing any IP. So if a country is provided in the json, it should ignore source IP which is the one of the proxy anyway.

**Comment by adriaanvanrossum** [comment]
> [...] I was wondering if I could just update the hostname and cdn parameter inside hello.js to pass this towards a script on our server which can do the POST of the JSON data [...]

This is totally possible. Just proxy the request to our API and we are happy to log it for you.

> So Analytics would have country information (so it could show a map) without ever seeing any IP.

This could also be done, we don't support the country field at the moment because we base the geo location of the visitor on [time zones in the browser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions). This is a more privacy friendly approach and every country has their own time zone(s).

> So if a country is provided in the json, it should ignore source IP which is the one of the proxy anyway.

We always ignore the IP address. See [our docs](https://docs.simpleanalytics.com/what-we-collect#ip-addresses) for more information.

**Comment by Bramzor** [comment]
Thanks for the confirmation. Will check what the best approach can be.

Probably the best way is to log everything to a queue and process it in batches or maybe even by parsing the logs. But I assume it isn't possible yet to send a list of events (which would make it more efficient for your side and ours, with a reasonable limit of course)? Also it seems timestamp is not available in the API which is required if we would delay/group log events.

In the meantime, being able to proxy already solves the privacy thing.

**Comment by adriaanvanrossum** [comment]
We want to integrate batch processing for our own scripts as well. Having less writes in a table with a lot of reads increases the performance quite a bit. We already have a queue, so we need to create an endpoint where you can add batches to the queue. Adding a timestamp would be sufficient I suppose?

**Comment by Bramzor** [comment]
Sounds great. Timestamp might be ok although not all servers/clients might be in sync (use the same NTP, especially clients) and it might be required for the analytics to work properly? Maybe a delta makes more sense because you could still use the time of the analytics servers/queues as it is now but you calculate the delta for each item in the batch by doing (servertimestamp - delta of the item = servertimestamp of the item)? So if the customer/user his timestamp is totally off, it wouldn't impact the analytics at all as the call will just hold, x ms or x seconds ago this happened. Or you could still use the timestamps but also require them to provide the currenttimestamp so you can calculate the deltas on your side and use these. (currenttimestamp parameter - eventtimestamp parameter = event delta) Also you would want to calculate the delta asap, preferably even before the queue is processing it.

**Comment by adriaanvanrossum** [comment]
Added to our roadmap, will keep this issue open until it's added.

https://simpleanalytics.io/roadmap#116487

**Comment by adriaanvanrossum** [comment]
Created an issue for this in the main roadmap repo.
