### ISSUE TITLE
Incorrect Device when Chrome developer tools are used

### ISSUE THREAD

**Issue by Bramzor** [simpleanalytics/cdn#4]
Noticed that the width was off when Chrome Developer tools is open.
Probably this is because innerWidth is used. Not sure if outerWidth would be better or a combination of the 2.
An example of how these 2 are used to detect if the developer window is open: https://github.com/sindresorhus/devtools-detect/blob/master/index.js

My guess is that using outerWidth would already solve it?

**Comment by adriaanvanrossum** [comment]
We do this on purpose. `innerWidth` is the actual size the website is viewed in. 

<kbd><img width="1440" alt="CleanShot 2019-06-06 at 10 52 22@2x" src="https://user-images.githubusercontent.com/1079135/59019917-6e34a200-8838-11e9-800f-895b1250601f.png"></kbd>

We don't want to get device width, but website width. To get the actual device we collect it's info based on the user agent of the visitor.

It's not all visible in our interface yet, but it's available in our API: https://simpleanalytics.io/simpleanalytics.io.json

Does this satisfy your use case?

**Comment by Bramzor** [comment]
Hmm, in that case it must be something else. For some reason {\"url\":\"-/\",\"ua\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36\",\"width\":852,\"timezone\":\"Europe/Brussels\" translates in the Analytics towards a Tablet to 992px, while Im pretty sure I'm working on a laptop right now. That is why I thought about the innerWidth causing the issue.

**Comment by adriaanvanrossum** [comment]
This is indeed the current behavior. The device width is summarized to a device type, which is incorrect in some cases. Devices are basically device inner widths. Not devices. We will fix this incorrect behavior.

**Comment by adriaanvanrossum** [comment]
This is fixed a long time ago ;)
